### ISSUE TITLE
selfsigned_certificate error

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#95]
When using new atscm >= V0.4.0, a certification error occurs. 
Seems to be a node-opc-ua related isssue. 
Debugging it lead me to the fact that the url used by node-opc-ua for the certificate is no longer accessible for some reason.

This can be temporarily fixed by copying a certification from another (working) atscm project.

**Steps to reproduce error**

 - atscm init
 - atscm pull

**Original error message**

![atscm050-pull-certificate error](https://user-images.githubusercontent.com/34569639/34102516-c2facb74-e3e9-11e7-8684-cc9d08b0254c.PNG)

 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=0.4.0 | 
| atscm-cli     |     0.3.0 | 
| atvise server | 2.5.9 & 3.2.0 |
| node          |          9.3.0 | 
| npm           |           5.6.0 |

**Comment by IngMichaelMayr** [comment]
**_Just for your notice:_**

There is some kind of **"workaround"**.
If there is another, "older" version of the atscm installation, where the certification download url worked,
you can copy those certification-information from this project to the new project.

Here is the location where you find those files and folders. On the new project you have to insert it under the same subfolders

![nodeopcua-certification](https://user-images.githubusercontent.com/34569639/36201458-4dc7fe02-1180-11e8-9d30-f3c50fff4894.png)

**Comment by Grwmagad** [comment]
I run into the same Problem and fixed this here.
I always got an error when installing that the openssl.exe seems to be no valid Win32 exe.
So I downloaded the openssl package manually [here](http://indy.fulgan.com/SSL/openssl-1.0.2d-i386-win32.zip) and copied it during the "_atscm init_" process into the ..atscm\node_modules\node-opcua-pki\bin\openssl folder when the system prompted that it wants to open the openssl.exe.

**Comment by LukasHechenberger** [comment]
This problem occurs with a single version of *node-opcua*. As the author of this module **does not follow semantic versioning**, and as npm < 5 doesn't use lockfiles on dependencies, this specific version may have been installed in your case. Updating to npm v5 or, even better, v6 (with `npm i -g npm`) should solve this, as they use the exact version of *node-opcua* specified in this project's *package-lock.json*.

Feel free to reopen this issue if you're having any further problems.

**Comment by IngMichaelMayr** [comment]
Hi,

sorry to say, but still getting this error. I updated npm to the Version 6.1.0.
Some tries lead to the insight, that the suggested solution of Grwmagad worked, but is not feasible for daily use. A better approach is appreciated.

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=0.6.0 |
| atscm-cli     |     0.5.0 |
| atvise server | 3.2.0 |
| node          |          9.3.0 |
| npm           |           6.1.0 |
</details>

**Comment by LukasHechenberger** [comment]
Finally reproducible: [Our windows tests](https://ci.appveyor.com/project/LukasHechenberger/atscm/build/1.0.665/tests) currently fail because of this issue.

**Comment by IngMichaelMayr** [comment]
Seems to be fixed in version beta 22
